version: 2

sources:
  - name: raw
    description: "Raw data layer in Snowflake"
    database: DBT_PRACTICE
    schema: RAW
    tables:
      - name: customers
      - name: orders
      - name: payments
